language: java
sudo: false
install: true

services:
  - docker

jdk:
  - openjdk11

env:
  - DOCKER_FILE=/docker/arm/Dockerfile DOCKER_NAME=asck-survey DOCKER_TAG=arm-latest

addons: 
  sonarcloud:
      organization: "uniqueck-github"
      token:
        secure: $SONAR_TOKEN
  apt:
    packages:
      - graphviz


jobs:   
  include:   
    - stage: build and test
      if: NOT branch = develop OR type = pull_request 
      script: mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent compile sonar:sonar -Dsonar.projectKey=uniqueck_feedback-system 
    - stage: build, test and deploy to docker hub
      if: branch = develop AND NOT type = pull_request
      # login to docker hub
      before_script:
      - docker run --rm --privileged multiarch/qemu-user-static:register --reset
      - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent compile sonar:sonar -Dsonar.projectKey=uniqueck_feedback-system
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      script:
      - docker build --build-arg JAR_FILE=./target/asck-survey-*.jar -t $DOCKER_NAME -f $DOCKER_FILE .
      - docker images
      - docker tag $DOCKER_NAME $DOCKER_USERNAME/$DOCKER_NAME
      - docker push $DOCKER_USERNAME/$DOCKER_NAME:$DOCKER_TAG

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    
notifications:
  email: false
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
